/* ============================================================
   Streamer University 2026 roster — Hendrix College edition.
   Logins sourced from streameruniversity2026.com and verified
   against Twitch. Edit freely; `role` is optional.
   ============================================================ */

const ROSTER_2026 = [
  // ---- faculty & staff ----
  { login: "kaicenat", name: "Kai Cenat", role: "Principal" },
  { login: "agent00", name: "Agent00", role: "Professor" },
  { login: "duke", name: "Duke Dennis", role: "Professor" },
  { login: "cinna", name: "Cinna", role: "Professor" },
  { login: "thesushidragon", name: "SushiDragon", role: "Professor" },
  { login: "ludwig", name: "Ludwig", role: "Professor" },
  { login: "kaiyacenat1", name: "Kaiya", role: "Professor" },
  { login: "poudii", name: "Poudii", role: "Professor" },
  { login: "adapt", name: "Adapt", role: "Professor" },
  { login: "lizzobetwitchin", name: "Lizzo", role: "Professor" },
  { login: "valkyrae", name: "Valkyrae", role: "Professor" },
  { login: "pokimane", name: "Pokimane", role: "Professor" },
  { login: "maya", name: "Maya", role: "Professor" },
  { login: "nicknayersina", name: "Nick Nayersina", role: "Club Director" },
  { login: "lifeofproto", name: "Proto", role: "Club Director" },
  { login: "tpain", name: "T-Pain", role: "Club Director" },
  { login: "markusking", name: "Markus King", role: "Club Director" },
  { login: "markellwashington", name: "Markell Washington", role: "Club Director" },
  { login: "fanum", name: "Fanum", role: "Campus Police" },
  { login: "walton", name: "Walton", role: "Campus Police" },
  { login: "yourragegaming", name: "YourRAGE", role: "Guidance Counselor" },
  { login: "devontecenat", name: "Devonte Cenat", role: "Janitor" },
  { login: "kelo", name: "Kelo", role: "Janitor" },
  { login: "chrisnxtdoor", name: "ChrisNxtDoor", role: "Janitor" },
  { login: "ijustlovepuzzles", name: "iJustLovePuzzles", role: "Librarian" },
  // ---- class of 2026 ----
  { login: "2xceeej", name: "2xceeej" },
  { login: "a2guapo", name: "A2Guapo" },
  { login: "aikooofficial", name: "Aikoo" },
  { login: "aishahsofey", name: "Aishah Sofey" },
  { login: "amberrtyson", name: "AmberrTyson" },
  { login: "andrewuhrik", name: "Andrew Uhrik" },
  { login: "angelcrackedu", name: "AngelCrackedU" },
  { login: "aozami", name: "Aozami" },
  { login: "avazura", name: "Avazura" },
  { login: "benjychavez_", name: "Benjy Chavez" },
  { login: "real_bigant26", name: "Big Ant" },
  { login: "blasianbeautyalexis", name: "Blasian Beauty Alexis" },
  { login: "blazian", name: "Blazian" },
  { login: "bonita", name: "Bonita" },
  { login: "bonnie", name: "Bonnie" },
  { login: "braeden", name: "Braeden" },
  { login: "carterefe", name: "Carter Efe" },
  { login: "catrnado", name: "Catrnado" },
  { login: "chakrashooter", name: "ChakraShooter" },
  { login: "chrisgonecrazylive", name: "Chris Gone Crazy" },
  { login: "clarence_nyc", name: "ClarenceNYC" },
  { login: "coolbutterflyyyy", name: "CoolButterflyyyy" },
  { login: "coolitshawty", name: "Coolitshawty" },
  { login: "crystalizaguirre", name: "Crystal Izaguirre" },
  { login: "cutegunz", name: "CuteGunz" },
  { login: "damiilive", name: "DamiiLive" },
  { login: "davis", name: "Davis" },
  { login: "dcthadesigner", name: "DC Tha Designer" },
  { login: "dopeboyoli", name: "DopeBoyOli" },
  { login: "dreamdoll", name: "DreamDoll" },
  { login: "e11ysa", name: "E11ysa" },
  { login: "edwardkso", name: "EdwardKSo" },
  { login: "elinameng", name: "Elina Meng" },
  { login: "ezee", name: "Ezee" },
  { login: "findjeremiah", name: "FindJeremiah" },
  { login: "flako", name: "FLAKO" },
  { login: "flippenjosh", name: "FlippenJosh" },
  { login: "ftgioo", name: "Ft. Gioo" },
  { login: "fumibean", name: "Fumibean" },
  { login: "ilikehaskell", name: "iLikeHaskell" },
  { login: "iwantacinnamonroll", name: "IWantACinnamonRoll" },
  { login: "iwastori", name: "IWasTori" },
  { login: "jadamalaytv", name: "JadaMalayTV" },
  { login: "jaidabunni", name: "JaidaBunni" },
  { login: "jasontheween", name: "JasonTheWeen" },
  { login: "jaymommy0", name: "JayMommy" },
  { login: "jordynlucas", name: "Jordyn Lucas" },
  { login: "jshock9nine", name: "JShock9nine" },
  { login: "juicyjacob", name: "JuicyJacob" },
  { login: "kaneljoseph", name: "Kanel Joseph" },
  { login: "kicosmic", name: "KiCosmic" },
  { login: "kierapleaze", name: "Kiera Please" },
  { login: "kiiingjojo", name: "KiiingJojo" },
  { login: "king68thegreat", name: "King68TheGreat" },
  { login: "lacy", name: "Lacy" },
  { login: "lailasimonetv", name: "Laila Simone" },
  { login: "lanializa", name: "Lanializa" },
  { login: "theycallmeleii", name: "Leii" },
  { login: "luhliv1", name: "LuhLiv" },
  { login: "madaichakell", name: "Madai Chakell" },
  { login: "madi2hottyy", name: "Madi2Hotty" },
  { login: "malek_04", name: "Malek" },
  { login: "malibuandre", name: "MalibuAndre" },
  { login: "mandoomillions", name: "MandooMillions" },
  { login: "marlea", name: "Marlea" },
  { login: "marlon", name: "Marlon" },
  { login: "mcqueennlive", name: "McQueen" },
  { login: "meesterkeem", name: "MeesterKeem" },
  { login: "therealmiyalive", name: "Miya" },
  { login: "mookie", name: "Mookie" },
  { login: "myanicolelive", name: "Mya Nicole" },
  { login: "therealnialovee", name: "Nia Love" },
  { login: "noemi", name: "Noemi" },
  { login: "notbilzo", name: "NotBilzo" },
  { login: "notquitelikedub", name: "NotQuiteLikeDub" },
  { login: "officedrummer", name: "OfficeDrummer" },
  { login: "onlylarryking", name: "OnlyLarryKing" },
  { login: "paybae", name: "PayBae" },
  { login: "pittbully__", name: "PittBully (Rizz)" },
  { login: "plaqueboymax", name: "PlaqueBoyMax" },
  { login: "pudgie16", name: "Pudgie" },
  { login: "queennaija", name: "Queen Naija" },
  { login: "raphaelsololive", name: "Raphael Solo" },
  { login: "rawdogmoon", name: "RawDogMoon" },
  { login: "reemknocks", name: "ReemKnocks" },
  { login: "regtoofunny", name: "RegTooFunny" },
  { login: "rizpyyt", name: "RizpyYT" },
  { login: "rulaempire", name: "Rula Empire" },
  { login: "runiktvlive", name: "RunikTV" },
  { login: "sarasaffari", name: "Sara Saffari" },
  { login: "sarahfarrugia", name: "Sarah Farrugia" },
  { login: "seleolu", name: "Seleolu" },
  { login: "shazdelicious", name: "Shaz Delicious" },
  { login: "itsshonyx", name: "Shonyx" },
  { login: "sierrasprague", name: "Sierra Sprague" },
  { login: "silky", name: "Silky" },
  { login: "skaijackson", name: "Skai Jackson" },
  { login: "thesketchreal", name: "Sketch" },
  { login: "smokecertified", name: "SmokeCertified" },
  { login: "s0pink", name: "SoPink" },
  { login: "stableronaldo", name: "Stable Ronaldo" },
  { login: "stanleyymeng", name: "Stanley Meng" },
  { login: "straight2thbank__", name: "Straight2thBank" },
  { login: "suburbbaby", name: "Suburb Baby" },
  { login: "suhmmiee", name: "Suhmmiee" },
  { login: "sukiimellow", name: "SukiMellow" },
  { login: "tatumbittick", name: "Tatum Bittick" },
  { login: "taylorjasminee", name: "Taylor Jasmine" },
  { login: "thatsdaveontv", name: "ThatsDaveOnTV" },
  { login: "themightyba", name: "TheMightyBA" },
  { login: "therealtianamusarra", name: "Tiana Musarra" },
  { login: "wabewrld", name: "WabeWrld" },
  { login: "wardrobewinter", name: "WardrobeWinter" },
  { login: "wrldkailee", name: "WRLDKailee" },
  { login: "xscapeverse", name: "XscapeVerse" },
  { login: "yaboyywill", name: "YaBoyyWill" },
  { login: "ynlgeo", name: "YNL Geo" },
  { login: "ysabellagrace", name: "Ysabella Grace" },
  { login: "yugi2x", name: "Yugi2x" },
  { login: "yusuf7n", name: "Yusuf7n" },
];

/* Class of 2025 (University of Akron) — optional via the roster drawer. */
const ROSTER_2025 = [
  { login: "ddg", name: "DDG", role: "Professor '25" },
  { login: "indialovewestbrooks", name: "India Love", role: "Professor '25" },
  { login: "im_dontai", name: "ImDontai", role: "Professor '25" },
  { login: "extraemily", name: "ExtraEmily", role: "Professor '25" },
  { login: "preacherquis", name: "PreacherQuis", role: "Professor '25" },
  { login: "aimhigh", name: "AimHigh", role: "Professor '25" },
  { login: "blou", name: "B. Lou", role: "Professor '25" },
  { login: "funnymarco", name: "Funny Marco", role: "Professor '25" },
  { login: "bendadonnn", name: "BenDaDonn", role: "Professor '25" },
  { login: "ojaysuave", name: "Ojay Suave", role: "Counselor '25" },
  { login: "honeyyjade", name: "HoneyyJade" },
  { login: "tbvnks", name: "Tbvnks" },
  { login: "iloswork", name: "ILosWork" },
  { login: "brooklynfrost", name: "Brooklyn Frost" },
  { login: "sarahynh", name: "Sarahynh" },
  { login: "myrennmakayla", name: "My'ren Makayla" },
  { login: "yagirldes03", name: "YaGirlDes" },
  { login: "justfolass", name: "Folass" },
  { login: "scumtk", name: "ScumTK" },
  { login: "shell0", name: "Shell0" },
  { login: "iamtrinitij", name: "IAmTrinitiJ" },
  { login: "chicklethf", name: "Chicklet HF" },
  { login: "ninadaddyisback", name: "Nina" },
  { login: "aaverieiman", name: "Aaverie Iman" },
  { login: "nolimitjay", name: "NoLimitJay" },
  { login: "ggtwinsz", name: "GGTwinsz" },
  { login: "meyiram", name: "Meyiram" },
  { login: "lightskinmonte", name: "LightskinMonte" },
  { login: "yonnajay", name: "Yonna Jay" },
  { login: "shankcomics", name: "Shank" },
  { login: "sophiehyder", name: "Sophie Hyder" },
  { login: "brischeese", name: "Brischeese" },
  { login: "reginald", name: "Reggie" },
  { login: "jankyrondo", name: "JankyRondo" },
  { login: "tyronebee", name: "TyroneBee" },
  { login: "dannybans", name: "Danny Bans" },
  { login: "ripitrandy", name: "RipItRandy" },
  { login: "ayemari", name: "AyeMari" },
  { login: "esti", name: "Esti" },
  { login: "totaamc", name: "MC Tota" },
  { login: "summyahmarie", name: "SummyahMarie" },
  { login: "barbieskie", name: "Barbieskie" },
  { login: "izzy_kinda", name: "Izzy Kinda" },
  { login: "malenicruz", name: "Maleni Cruz" },
  { login: "thehoodbabies", name: "HoodBabies" },
  { login: "wendolynortizz", name: "Wendy Ortiz" },
  { login: "evelynomadera", name: "Evelyn Ortiz" },
  { login: "therealbigwinnn", name: "BigWinnn" },
  { login: "2xrakai", name: "RaKai" },
  { login: "maxwellye_", name: "Maxwell Ye" },
  { login: "2kboo", name: "2KBoo" },
  { login: "corey2u", name: "Corey2U" },
  { login: "ayaatanjali", name: "Aya" },
  { login: "viccgotti", name: "Vicc Gotti" },
  { login: "keeyahthecreator", name: "KeeyahTheCreator" },
  { login: "ginamarialaitschek", name: "Gina Laitschek" },
  { login: "junniehime", name: "JunnieHime" },
  { login: "snowcone", name: "Snowcone" },
  { login: "mrschimchim", name: "MrsChimChim" },
  { login: "imbadkidjay", name: "BadKidJay" },
  { login: "shaqqwith2qs", name: "ShaqqWith2Qs" },
  { login: "quan", name: "Quan" },
  { login: "3xpunga", name: "Punga" },
  { login: "ryaah", name: "Ryah" },
  { login: "autumnreigntaylor", name: "Autumn Reign Taylor" },
  { login: "valan", name: "Valan" },
  { login: "pixeldrinky", name: "PixelDrink" },
  { login: "deshaefrost", name: "Deshae Frost" },
  { login: "malachiwyd", name: "MalachiWYD" },
  { login: "crispymo_", name: "CrispyMo" },
  { login: "emilycc", name: "EmilyCC" },
  { login: "sarasheehan", name: "Sara Sheehan" },
  { login: "mari", name: "Mari" },
  { login: "howloudy", name: "Vanessa Loud" },
  { login: "saltygummibear", name: "SaltyGummibear" },
  { login: "youngdabo", name: "Young Dabo" },
  { login: "arky", name: "Arky" },
  { login: "iamvboogie", name: "VBoogie" },
  { login: "ashalk", name: "Ash Alk" },
  { login: "samham", name: "SamHam" },
  { login: "imallisonkroes", name: "Allison Kroes" },
  { login: "rayasianboy", name: "RayAsianBoy" },
  { login: "btbdezzz", name: "BTB Dezz" },
  { login: "thickneyy", name: "Thickney" },
  { login: "fbjamal", name: "Jamal" },
  { login: "kingsammelot", name: "KingSammelot" },
  { login: "caiuwus", name: "Caiuwus" },
  { login: "taeda_geez", name: "Taeda Geez" },
  { login: "jaycinco", name: "Jay Cinco" },
  { login: "shollykns", name: "Sholly KNS" },
  { login: "yasirshakor", name: "Okaysirr" },
  { login: "tylil", name: "Tylil" },
  { login: "marcasist", name: "Marcasist" },
  { login: "thelalabaptiste", name: "LaLa Baptiste" },
  { login: "treasureosiria", name: "Treasure Osiria" },
  { login: "turahbaby", name: "Turahbaby" },
  { login: "lightskinkimm", name: "Lightskin Kim" },
  { login: "catalixia", name: "Catalixia" },
  { login: "kokonata", name: "KokoNata" },
  { login: "aldogotit_", name: "AldoGotIt" },
  { login: "nizzy_", name: "Nizzy" },
  { login: "thezeddywill", name: "Zeddy Will" },
  { login: "rynenzo", name: "Rynenzo" },
  { login: "evelynandbobby", name: "Evelyn & Bobby" },
  { login: "kanklive", name: "KankLive" },
  { login: "emildztv", name: "EmilDzTV" },
  { login: "iluvucynthia", name: "ILuvUCynthia" },
  { login: "karelesskitty", name: "KarelessKitty" },
  { login: "blasianbabylola", name: "BlasianBabyLola" },
  { login: "itskbakes", name: "Kbakes" },
  { login: "primatepaige", name: "PrimatePaige" },
  { login: "daejorno", name: "Daejorno" },
  { login: "ivansbetter", name: "IvansBetter" },
  { login: "alexandjessicaa", name: "Alex & Jessica" },
  { login: "bdestined", name: "BDestined" },
  { login: "jptgamez", name: "JPT Games" },
  { login: "kishka", name: "Kishka" },
  { login: "raud", name: "Raud" },
  { login: "yohanuja", name: "Yohan Uja" },
  { login: "datboigio_", name: "DatBoiGio" },
  { login: "bribretv", name: "BribreTV" },
  { login: "jamworldtv", name: "Jam World TV" },
  { login: "mayabuckets", name: "MayaBuckets" },
];
